[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/api/*"
  to = "https://metamorphose-backend.onrender.com/api/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/media/*"
  to = "https://metamorphose-backend.onrender.com/media/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
